//import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { SessionProvider } from "@/hooks/useSession";
import InactivityLogout from "@/components/InactivityLogout";

/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

className={`${geistSans.variable} ${geistMono.variable} antialiased`} */

export const metadata = {
  title: "Janta Power",
  icons: {
    icon: "/images/favicon.ico",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const nonce = (await headers()).get("x-nonce") || undefined;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          nonce={nonce}
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html: `(function(){var t=localStorage.getItem('theme');if(t==='dark'||(!t&&window.matchMedia('(prefers-color-scheme: dark)').matches))document.documentElement.classList.add('dark');else document.documentElement.classList.remove('dark');})();`,
          }}
        />
      </head>
      <body>
        <ThemeProvider>
          <SessionProvider>
            <InactivityLogout />
            {children}
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
